### ISSUE TITLE
gpib_bitbang driver needs a tweak to make it work with Driver IC version

### ISSUE THREAD

**Issue by Symon3** [elektronomikon/raspi_gpib_driver#5]
As noted, the raspi_gpib_driver has been integrated into linux-gpib (https://linux-gpib.sourceforge.io/) with Version 4.3.4 as a general "gpib_bitbang" driver, please use the official source or package.
I imagine this works fine with the board built as a passive adapter. However, if using the GPIB driver board with the driver ICs fitted, then this file needs an edit before recompiling.
linux-gpib-4.3.4/linux-gpib-kernel-4.3.4/drivers/gpib/gpio/gpib_bitbang.c
Uncomment these lines 717-720, 762, 862-864, 876-878
This allows the pullup enable (PE), direction control (DC) and talk enable (TE) signals to be driven from the Pi, without which there can be no communications. Line 762 allows the green LED to work.
Suggestion, future revision could use another GPIO with a pullup or pulldown to signal to the driver which version of board is attached. Or drive the control signals anyway.
I hope this helps.

**Comment by elektronomikon** [comment]
Hi Symon,
thanks for your input!
We are currently preparing the next release, you can look at a beta version at
https://sourceforge.net/p/linux-gpib/code/HEAD/tree/trunk/linux-gpib-kernel/drivers/gpib/gpio/gpib_bitbang.c

which has a parameter "sn7516x_used" for the kernel module to enable the PE, DC and TE lines.

have fun,
Thomas
